services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: cloudspire_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hotel_management
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloudspire_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  # API Backend Laravel
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cloudspire_api
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=hotel_management
      - DB_USERNAME=hotel_user
      - DB_PASSWORD=hotel_password
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "./backend:/var/www"
      - storage_data:/var/www/storage
    ports:
      - "8000:8000"
    networks:
      - cloudspire_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cloudspire_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - cloudspire_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
  storage_data:

networks:
  cloudspire_network:
    driver: bridge
